### ISSUE TITLE
Re centre longitude

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/SOmap#34] opened 2019-04-04 03:56 UTC
Just parking this here for now. 

```R
  st_recenter <- st_recentre <- function(x, clon = NULL, ..., tryfix = TRUE) {
  if (is.null(clon)) return(x)
  if (!st_is_longlat(x)) stop("recentring not appropriate for non longlat data")
  ## save the crs while we do our munging
  crs <- st_crs(x)
  x <- st_set_crs(x, NA)
  
  
  ## try to fix problematic geometry
  if (tryfix) {
   if (all(grepl("POLYGON", st_geometry_type(x)))) x <- suppressWarnings(st_buffer(sf::st_as_sf(x), 0))
   x <- st_wrap_dateline(x, options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))
  }
  wbox <- st_bbox(c(xmin = -180, ymin = -90, xmax = (clon)%%360 - 180, ymax = 90))
  west <- suppressWarnings(st_crop(x, wbox))
  west <- st_set_geometry(west, st_geometry(west) + c(360, 0))
  east <- suppressWarnings(st_crop(x, st_bbox(c(xmin = (clon)%%360 - 180, xmax = 180, ymin = -90, ymax = 90))))
  xx <- rbind(
    west, east
 ) 
  ## ensure geometries are of consistent type
  xx <- sf::st_cast(xx)
  bb <- st_bbox(xx)
  ## hmmm
  # if (bb["xmax"] > 180 && !grepl("\\+over", crs) && !grepl("init", crs)) {
  #   crs <- sprintf("%s +over", crs)
  # }
  st_set_crs(xx, crs)
}
```

Code copied from https://gist.github.com/mdsumner/2be160dcd66f35893e4e7c926f264c22 sparked by discussions https://twitter.com/djnavarro/status/1105765978326159361

**Comment by mdsumner** [comment] 2019-08-28 13:00
An example inspired on [twitter](https://twitter.com/mdsumner/status/1166678921544257536): 

``` r
  recentre <- function(x, clon = NULL, ..., tryfix = TRUE) {
    if (is.null(clon)) return(x)
    if (!st_is_longlat(x)) stop("recentring not appropriate for non longlat data")
    ## save the crs while we do our munging
    crs <- st_crs(x)
    x <- st_set_crs(x, NA)
    
    
    ## try to fix problematic geometry
    if (tryfix) {
      if (all(grepl("POLYGON", st_geometry_type(x)))) x <- suppressWarnings(st_buffer(sf::st_as_sf(x), 0))
      x <- st_wrap_dateline(x, options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))
    }
    wbox <- st_bbox(c(xmin = -180, ymin = -90, xmax = (clon)%%360 - 180, ymax = 90))
    west <- suppressWarnings(st_crop(x, wbox))
    west <- st_set_geometry(west, st_geometry(west) + c(360, 0))
    east <- suppressWarnings(st_crop(x, st_bbox(c(xmin = (clon)%%360 - 180, xmax = 180, ymin = -90, ymax = 90))))
    xx <- rbind(
      west, east
    ) 
    ## ensure geometries are of consistent type
    xx <- sf::st_cast(xx)
    bb <- st_bbox(xx)
    st_set_crs(xx, crs)
  }
  
library(sf)

x <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
msx <- rmapshaper::ms_simplify(x, keep = 0.99)

all(st_is_valid(msx))
#> [1] TRUE
plot(recentre(msx, clon = -152)[4])
#> Warning in CPL_wrap_dateline(st_geometry(x), options, quiet): GDAL Error
#> 1: IllegalArgumentException: Points of LinearRing do not form a closed
#> linestring
#> Warning in CPL_wrap_dateline(st_geometry(x), options, quiet): GDAL Error
#> 1: IllegalArgumentException: Points of LinearRing do not form a closed
#> linestring
#> Warning in st_is_longlat(x): bounding box has potentially an invalid value
#> range for longlat data
```

![](https://i.imgur.com/HONhUAO.png)

<sup>Created on 2019-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdsumner** [comment] 2019-08-28 13:09
Add a group by summarize to remove the seam

``` r
  recentre <- function(x, clon = NULL, ..., tryfix = TRUE) {
    if (is.null(clon)) return(x)
    if (!st_is_longlat(x)) stop("recentring not appropriate for non longlat data")
    ## save the crs while we do our munging
    crs <- st_crs(x)
    x <- st_set_crs(x, NA)
    
    
    ## try to fix problematic geometry
    if (tryfix) {
      if (all(grepl("POLYGON", st_geometry_type(x)))) x <- suppressWarnings(st_buffer(sf::st_as_sf(x), 0))
      x <- st_wrap_dateline(x, options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))
    }
    wbox <- st_bbox(c(xmin = -180, ymin = -90, xmax = (clon)%%360 - 180, ymax = 90))
    west <- suppressWarnings(st_crop(x, wbox))
    west <- st_set_geometry(west, st_geometry(west) + c(360, 0))
    east <- suppressWarnings(st_crop(x, st_bbox(c(xmin = (clon)%%360 - 180, xmax = 180, ymin = -90, ymax = 90))))
    xx <- rbind(
      west, east
    ) 
    ## ensure geometries are of consistent type
    xx <- sf::st_cast(xx)
    bb <- st_bbox(xx)
    ## hmmm
    # if (bb["xmax"] > 180 && !grepl("\\+over", crs) && !grepl("init", crs)) {
    #   crs <- sprintf("%s +over", crs)
    # }
    st_set_crs(xx, crs)
  }
  
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.2, PROJ 5.2.0

x <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
msx <- rmapshaper::ms_simplify(x, keep = 0.99)

all(st_is_valid(msx))
#> [1] TRUE
library(dplyr)
rsx <- recentre(msx, clon = -152) %>% group_by(sovereignt) %>% summarize()
#> Warning in CPL_wrap_dateline(st_geometry(x), options, quiet): GDAL Error
#> 1: IllegalArgumentException: Points of LinearRing do not form a closed
#> linestring
#> Warning in CPL_wrap_dateline(st_geometry(x), options, quiet): GDAL Error
#> 1: IllegalArgumentException: Points of LinearRing do not form a closed
#> linestring
plot(rsx)
#> Warning in st_is_longlat(x): bounding box has potentially an invalid value
#> range for longlat data
```

![](https://i.imgur.com/b9URpad.png)

<sup>Created on 2019-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MartinBeal** [comment] 2019-11-07 10:29
Any idea how to add vertices to polygons split along the new antimeridian? 

![recentered_worldmap](https://user-images.githubusercontent.com/45400296/68381175-11237c00-0149-11ea-804f-f0e2cb5b4e26.png)

I've imagined buffering a line along the antimeridian to identify the intersecting polygons, but not sure how to add vertices in an appropriate fashion.

**Comment by mdsumner** [comment] 2019-11-07 10:39
probably `st_segmentize(x, 0.5)` *before* reprojection (0.5 being in longlat degrees). But it can take a bit of plumbing - what's this projection? Robinson? "+proj=robin +lon_0=180"?

**Comment by mdsumner** [comment] 2019-11-07 11:05
Sheesh, and beware - st_segmentize works in *metres* (now I think), but st_buffer will accept degrees ...  currently waiting to kill my process to see if it can work

(a small negative buffer is required to avoid wrap when reprojecting)

**Comment by mdsumner** [comment] 2019-11-07 11:40
This seems to work: 


```R
rsx <- recentre(x, 220)

plot(st_transform(st_segmentize(st_buffer(rsx[1], -0.001), 50000), "+proj=robin +lon_0=220"))

```

Note that the argument to st_buffer is *in degrees*, a tiny negative offset to get off the edge of the antimeridian and avoid wrapping, but the argument to st_segmentize is *in metres*  ***even though the data is in in longlat***. 

Don't use a tiny value in st_segmentize or you'll wait forever with no interrupt before the session crashes from memory overuse :)

Here's a reprex, with wrld_simpl because rnaturalearth is giving me grief - I had to tweak the buffer and the segmentizing to get  a nice result. 

``` r
  recentre <- function(x, clon = NULL, ..., tryfix = TRUE) {
  if (is.null(clon)) return(x)
  if (!st_is_longlat(x)) stop("recentring not appropriate for non longlat data")
  ## save the crs while we do our munging
  crs <- st_crs(x)
  x <- st_set_crs(x, NA)
  
  
  ## try to fix problematic geometry
  if (tryfix) {
    if (all(grepl("POLYGON", st_geometry_type(x)))) x <- suppressWarnings(st_buffer(sf::st_as_sf(x), 0))
    x <- st_wrap_dateline(x, options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))
  }
  wbox <- st_bbox(c(xmin = -180, ymin = -90, xmax = (clon)%%360 - 180, ymax = 90))
  west <- suppressWarnings(st_crop(x, wbox))
  west <- st_set_geometry(west, st_geometry(west) + c(360, 0))
  east <- suppressWarnings(st_crop(x, st_bbox(c(xmin = (clon)%%360 - 180, xmax = 180, ymin = -90, ymax = 90))))
  xx <- rbind(
    west, east
  ) 
  ## ensure geometries are of consistent type
  xx <- sf::st_cast(xx)
  bb <- st_bbox(xx)
  ## hmmm
  # if (bb["xmax"] > 180 && !grepl("\\+over", crs) && !grepl("init", crs)) {
  #   crs <- sprintf("%s +over", crs)
  # }
  st_set_crs(xx, crs)
}

library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0

data("wrld_simpl", package = "maptools")
x <- sf::st_as_sf(wrld_simpl)
#> Loading required package: sp

rsx <- recentre(x, 220) 
#> Warning in CPL_wrap_dateline(st_geometry(x), options, quiet): GDAL Error
#> 1: IllegalArgumentException: Points of LinearRing do not form a closed
#> linestring

#> Warning in CPL_wrap_dateline(st_geometry(x), options, quiet): GDAL Error
#> 1: IllegalArgumentException: Points of LinearRing do not form a closed
#> linestring

plot(st_transform(st_segmentize(st_buffer(rsx[1], -0.001), 50000), "+proj=robin +lon_0=220"))
#> Warning in st_is_longlat(x): bounding box has potentially an invalid value
#> range for longlat data
#> Warning in st_buffer.sfc(st_geometry(x), dist, nQuadSegs, endCapStyle =
#> endCapStyle, : st_buffer does not correctly buffer longitude/latitude data
#> dist is assumed to be in decimal degrees (arc_degrees).
#> Warning in st_is_longlat(x): bounding box has potentially an invalid value
#> range for longlat data
#> Warning in st_is_longlat(x): bounding box has potentially an invalid value
#> range for longlat data
```

![](https://i.imgur.com/0e92TCH.png)

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MartinBeal** [comment] 2019-11-07 12:08
@mdsumner lovely! The more I reproduce a map/figure the more these little aesthetic things bug me! Thanks a million. 

Btw the projection I'm using is Kavraisky VII ("+proj=kav7 +lon_0=180")

**Comment by MartinBeal** [comment] 2019-11-07 13:04
Hmm when I play around with the antimeridian longitude it gets funny. Re-ran your code changing longitude to 207 (both in function and proj4string). 

![Rplot01](https://user-images.githubusercontent.com/45400296/68390613-90bb4600-015d-11ea-9d10-6a50eb86af20.png)

Trying different st_segmentize() distances didn't help much. 

`rsx <- recentre(x, 207)`
`plot(st_transform(st_segmentize(st_buffer(rsx[1], -0.001), 1000), "+proj=robin +lon_0=207"))`

![Rplot02](https://user-images.githubusercontent.com/45400296/68391056-9b2a0f80-015e-11ea-927d-e30666c7e760.png)

Seems to only work on multiples of 10.

**Comment by mdsumner** [comment] 2019-11-07 17:55
that's what I saw with tweaking - there's no systematic way to fix this, sometimes it requires a different data set or manual edits

**Comment by mdsumner** [comment] 2019-11-07 18:08
I get a good result with 

```R
x <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
msx <- rmapshaper::ms_simplify(x, keep = 0.99)
rsx <- recentre(msx, clon = -153) %>% group_by(sovereignt) %>% summarize()
plot(st_transform(st_segmentize(st_buffer(rsx, -0.01), 15000), "+proj=robin +lon_0=-153"))
```

I can't get anything out of kav7, fails at `st_crs("+proj=kav7")`

**Comment by MartinBeal** [comment] 2019-11-08 12:30
Ah ok gotcha.

kav7 projection works with: 
`plot(lwgeom::st_transform_proj(st_segmentize(st_buffer(rsx, -0.01), 15000), "+proj=kav7 +lon_0=-153"))`

Question about the recentre function. Should the `clon` argument be the degree value by which to shift the antimeridian, or the longitude (0,360) to which the antimerdian should be shifted (i.e. in this case 207 or -153) ?

**Comment by mdsumner** [comment] 2019-11-08 19:01
Oh nice, lwgeom good one.

I'm not sure it does this atm, but I'd want either outcome to work -153, or 207 - I meant to explore that and only changed the number

**Comment by raymondben** [comment] 2021-11-16 00:19
Closing because not an active SOmap issue

**Closed by raymondben** 2021-11-16 00:19 UTC
